[package]
name = "zed_mcp_server_signoz"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
lto = true
opt-level = "z"
strip = true
